apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 50Gi