apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app-deployment.appName }}
data:
  PUID: "1000"
  PGID: "1000"
  VERSION: {{ .Values.plexVersion }}
  # TODO figure out what this is for
  #PLEX_CLAIM: optional