apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "lscr.io/linuxserver/plex:{{ .Values.imageTag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}
          volumeMounts:
            - mountPath: /config
              name: {{ tpl .Values.volumeNames.config . }}
      volumes:
        - name: {{ tpl .Values.volumeNames.config . }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.volumeNames.config . }}
